### ISSUE TITLE
Fatal error!

### ISSUE THREAD

**Issue by ben72** [Billmate/woocommerce#365]
This renders Billmate unusable on WooCommerce sites. No good! Please fix asap!

The issue started 24-Dec-2019 17:36:27 UTC.

I've seen this on two different sites on different servers.

In the log:
```
[24-Dec-2019 17:36:27 UTC] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /home/pub/public_html/website/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-account.php:954
Stack trace:
#0 /home/pub/public_html/website/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-account.php(1008): WC_Gateway_Billmate_Partpayment::update_billmatepclasses_from_frontend()
#1 /home/pub/public_html/website/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-account.php(706): WC_Gateway_Billmate_Partpayment::payment_fields_options('387.00')
#2 /home/pub/public_html/website/wp-content/plugins/woocommerce/templates/checkout/payment-method.php(30): WC_Gateway_Billmate_Partpayment->payment_fields()
#3 /home/pub/public_html/website/wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include('/home/pub/...')
#4 /home/pub/public_html/website/wp-content/plugins/woocommerce/templates/checkout/payment.php(30): wc_get_template( in /home/pub/public_html/website/wp-content/plugins/billmate-payment-gateway-for-woocommerce/class-billmate-account.php on line 954
```

**Comment by ben72** [comment]
When deactivating Part Payment it goes back to normal and Billmate Invoice can be used. Puuuh!! 

Please take a look at this severe error asap as a lot of sites will most likely have the same issue.

I'm guessing the load of payment plans are failing.

**Comment by andyjohansson** [comment]
Hi @ben72 we are looking into the issue. Do you know if the error was introduced in version 3.8.1 or 3.8.0?

**Comment by ben72** [comment]
Thanks @andyjohansson It was the same with 3.7.x and 3.8.1. Could it be something server side when fetching payment plans?

**Comment by andyjohansson** [comment]
My theory is that as well. I've made some updates on out side now. Is the issue resolved now?

**Comment by ben72** [comment]
The issue is now resolved! What did you change?
Thanks for your help. I hope this glitch didn't affect too much for you! Here it affected lost sales for about 28h in 2 webshops. Hopefully not too many wanted to buy during 24-25/12.
Was it only WooCommerce or did it affect other platforms as well?

**Comment by andyjohansson** [comment]
Great to know.
All payment plans have a due date. Some plans expire 2019-12-31 and there was a code in WooCommerce which caused the pulling of new payment plans to fail if the plans were not yet updated. We try to update them in the background if they expire in less then one week. We were planning to update these tomorrow but I updated them now instead. We will look more into the issue sot that it does not occur again next year.

**Comment by ben72** [comment]
OK great to know. So you will probably not see any sales from WooCommerce sites with part payment active from 24-Dec-2019 17:36:27 UTC until now.
Note that this also affected all other sales as the checkout crashed with this error. You should work on making it fail gracefully. JS halted so it was not possible to choose any payment option.
Luckily we were notified by a customer about this. Also luckily I found the temporary fix to disable part payment so we got it working last night again.
Thanks for your relatively fast resolution! Much appreciated!

**Comment by DanielMarklund** [comment]
Just woke up to this issue. It looks like no customers have been able to do purchases for products that can be part payed since this issue came up – **and still cant!** This has resulted in a great loss in sales, which like last year happened at the same time - right in the Mellandagsrea campaign.

Everywhere the part payment widget shows up, it echos the error "The site is experiencing technical difficulties." and stops rendering the rest of the page.

What do we do to fix this now?

**Comment by ben72** [comment]
@DanielMarklund Do you show the part payment option on product pages? I don't so I wouldn't know how that works. The issue I had was that part payment broke the checkout so it was not possible to make any purchase. This was resolved when Billmate updated the payment plans yesterday. My temporary solution before that was to disable part payment in the WooCommerce payment settings.

**Comment by DanielMarklund** [comment]
Hi @ben72 , I don't have part payment activated as we're using Billmate Checkout only for Sweden. See the following image for more info on where it breaks the site:
<img width="755" alt="Skärmavbild 2019-12-27 kl  09 13 53" src="https://user-images.githubusercontent.com/1516103/71508775-3c913000-2889-11ea-9cc0-d907d3c92556.png">

Good to know is that we're still on Version 3.4.6 in production, as we have a bit more complex checkout page that seems to break from time to time when Billmate updates their plugin, so we're treading carefully. I'm currently implementing Version 3.8.1 but it breaks our shipping method selector so I haven't pushed it yet.

Temporary fix for us still on 3.4.6:
Comment out row 1032 in class-billmate-account.php:
//self::update_billmatepclasses_from_frontend();

**Comment by ben72** [comment]
@DanielMarklund OK, I'm on the latest version. And I'm using the native checkout, not Billmate checkout. Could it be a caching issue?! My sites started working again when Billmate updated the plans. What if you disable part payment, check that the page works and then enable it again and check if it works then?

**Comment by DanielMarklund** [comment]
@ben72 Thanks! Static cache, Redis, OP Cache, transients and customer sessions were all cleared. It did not solve the issue. Billmate Checkout doesn't have support for turning off individual payment gateways unfortunately – that is only supported in the native checkout. I've solved it temporarily with the fix in my last post here and will investigate further.

**Comment by stefanliden** [comment]
> Hi @ben72 , I don't have part payment activated as we're using Billmate Checkout only for Sweden. See the following image for more info on where it breaks the site:
> <img alt="Skärmavbild 2019-12-27 kl 09 13 53" width="755" src="https://user-images.githubusercontent.com/1516103/71508775-3c913000-2889-11ea-9cc0-d907d3c92556.png">
> 
> Good to know is that we're still on Version 3.4.6 in production, as we have a bit more complex checkout page that seems to break from time to time when Billmate updates their plugin, so we're treading carefully. I'm currently implementing Version 3.8.1 but it breaks our shipping method selector so I haven't pushed it yet.
> 
> Temporary fix for us still on 3.4.6:
> Comment out row 1032 in class-billmate-account.php:
> //self::update_billmatepclasses_from_frontend();

Thx Daniel, 
I have made a ticket to the developer about this problem. I will return to you when its fixt!

**Comment by MattiasNilsson** [comment]
This is solved in an earlier release.
